### PR TITLE
Removing JS Legacy compilation configurations

### PR DESCRIPTION
**Pull request by mvicsokolova**

### CODE REVIEW

**Comment by qwwdfsad** [comment]
Should it be `kotlin-community/dev` branch?

**Comment by mvicsokolova** [comment]
I'm now investigating the failing `JvmLegacyTransformationTest.testClasspath`, as it passes I'll merge all the changes to `kotlin-community/dev`

**Comment by qwwdfsad** [comment]
I mean, why isn't the PR targeted to `develop` with conditional disabling or legacy/JS?

**Comment by mvicsokolova** [comment]
I ran the build against Kotlin master: https://buildserver.labs.intellij.net/buildConfiguration/Kotlin_KotlinDev_kotlinxAtomicfu/295252721?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildChangesSection=true

**Comment by mvicsokolova** [comment]
I created the new PR from the updated branch (#296)

**Pull request closed without merging**
