### PR TITLE
Use pthread_mutex instead of a custom lock on Apple platforms

### PR DESCRIPTION
**Pull request by stefanhaustein**
Use pthread_mutex instead of a custom lock on Apple platforms, as for Darwin the kernel must support a lock to handle QoS properly, and a custom built lock using atomics – such as the one currently used in nativeMain/synchronized.kt – won't fit that model (atomics do not handle QoS)

See issue #462 for details.

This PR introduces a new apple target and splits nativeNonApple (with the custom lock) out of native, keeping the dependency on the remaining native code in both cases.

### CODE REVIEW

**Comment by stefanhaustein** [comment]
P.S.: I accidentally included .gitignore for local settings (should be fine) and some jre fetcher in settings... Should I re-generate?

**Comment by mvicsokolova** [comment]
Thank you! Looks good to me as the first solution 👍🏻
I just need to rebase these changes onto `develop` branch, as it contains a bunch of changes in the build scripts

**Comment by stefanhaustein** [comment]
Thanks! It probably makes sense to push the mutex pool up to the shared native part then?

**Comment by qwwdfsad** [comment]
>Does the pool make any sense here? T

Do you mean in lock implementation in general?
It does because otherwise lock allocation performance model drastically differs between platforms and we would like to avoid that. E.g. we know that lock allocation is cheap and do so in coroutines left and right

**Comment by stefanhaustein** [comment]
I have an updated implementation incorporating feedback here and from compose-kmp... Given the amount of changes, the simplest way forward seems to be to close this and to create a new PR after I have synced my fork.

**Pull request closed without merging**
