### PR TITLE
Version 0.21.0

### PR DESCRIPTION
**Pull request by mvicsokolova**

### CODE REVIEW

**Comment by qwwdfsad** [comment]
Some observations about the commit history we got here: there is a sequence of commits that exist out-of-context (e.g. neither tested nor thoroughly explained (e.g. 5f05039ed7d929942619158e2fb7288412f66dae), with the final issue that is fixed also non-tested. They should've been squashed, with the detailed explanation why the changes are done.

I'd suggest using https://github.com/Kotlin/kotlinx-kover/pull/386 as an inspiration: the Gradle tweaks are documented, the test is provided, the commit message is extensive (e.g. *why* file collection was replaced with the provider, not the fact it was done)

**Comment by mvicsokolova** [comment]
Thank you, yes, all these out-of-context commits from [c201c53](https://github.com/Kotlin/kotlinx-atomicfu/pull/305/commits/c201c5386ff749fdcc81250e257614a84b4a54ce) to [c41d50a](https://github.com/Kotlin/kotlinx-atomicfu/pull/305/commits/c41d50afeaf65465974cb3f028c19cf7810d3aa4) were merged with this PR: https://github.com/Kotlin/kotlinx-atomicfu/pull/303. My mistake they were not squashed. The issue fixed there was reproduced by the existing test `kotlinx.atomicfu.plugin.gradle.test.JvmLegacyTransformationTest`.

I can fix the history in this branch and merge it to master in a proper way (squash + extended comment).

I would also add comments to all the changes for future understanding (some of them were just caused by using the new KGP API).

**Comment by mvicsokolova** [comment]
Currently, the release is blocked by this issue #307 that is fixed here #308 (waiting for review and approval).
It is only reproduced for now with Kotlin `1.9.0-RC`, but I want to add the fix to this release.

**Comment by mvicsokolova** [comment]
Commit fixing the issue with building JVM-only projects merged ([88a5e14](https://github.com/Kotlin/kotlinx-atomicfu/pull/305/commits/88a5e144c948f46697d80d26dcb0a2a2d5b9b8e7)). 

`develop` history fixed

**Pull request merged**
