### PR TITLE
Add WebAssembly target

### PR DESCRIPTION
**Pull request by skuzmich**
Same implementation as in K/JS but without JsName annotations

### CODE REVIEW

**Comment by mvicsokolova** [comment]
Hi! @skuzmich could you please elaborate on the motivation of adding the `wasm` target?

**Comment by skuzmich** [comment]
> Hi! @skuzmich could you please elaborate on the motivation of adding the `wasm` target?

We need it to build kx.coroutines, which is a dependency for a lot of projects

**Comment by qwwdfsad** [comment]
I'm sorry, but who is going to maintain this target? Who is going to be responsible for it to work, for flaky builds, for compiler plugins, and for future build and development issues?

Was it agreed upon during our planning?

**Comment by skuzmich** [comment]
cc: @bashor

**Comment by bashor** [comment]
@qwwdfsad
Last time (in April 2022), we discussed that it could be done around 1.8.
Let's discuss this again and reach an agreement about key questions.

**Comment by skuzmich** [comment]
Decided to postpone merging Wasm target support to main branches. Wasm target support will be in `wasm` branch for now.

**Pull request closed without merging**
